# Generated by Django 5.2.7 on 2025-10-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='authorized_signers',
            field=models.ManyToManyField(blank=True, help_text='Specific staff members authorized to sign off this task. Leave empty to allow all staff.', related_name='authorized_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UnsignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_signed_at', models.DateTimeField(help_text='When original sign-off occurred')),
                ('original_score', models.CharField(blank=True, max_length=20)),
                ('original_notes', models.TextField(blank=True)),
                ('unsigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for removal')),
                ('original_signed_by', models.ForeignKey(help_text='Who originally signed off', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_signoffs_removed', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsign_logs', to='tracker.task')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsign_logs', to='tracker.trainee')),
                ('unsigned_by', models.ForeignKey(help_text='Who removed the sign-off', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsign_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unsigned_at'],
            },
        ),
    ]
