# Generated by Django 5.2.7 on 2025-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_authorized_signers_unsignlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(help_text='Display order (must be unique)', unique=True),
        ),
    ]
