# Generated by Django 5.2.7 on 2025-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minimum_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum passing score (only applies if task requires a score)', max_digits=5, null=True),
        ),
    ]
