# Generated by Django 5.2.7 on 2025-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_minimum_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Fall 2025', max_length=50, unique=True)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=10)),
                ('is_current_override', models.BooleanField(default=False, help_text='Manually set this cohort as current (overrides automatic detection)')),
            ],
            options={
                'ordering': ['-year', '-semester'],
                'unique_together': {('year', 'semester')},
            },
        ),
    ]
