# Generated by Django 5.2.7 on 2025-10-06 16:48

from django.db import migrations


def populate_cohorts(apps, schema_editor):
    """Parse existing trainee cohort strings and create Cohort objects"""
    Trainee = apps.get_model('tracker', 'Trainee')
    Cohort = apps.get_model('tracker', 'Cohort')

    # Get all unique cohort strings from trainees
    cohort_strings = Trainee.objects.values_list('cohort', flat=True).distinct()

    for cohort_str in cohort_strings:
        if not cohort_str:
            continue

        # Parse cohort string (e.g., "Fall 2025" -> semester="Fall", year=2025)
        parts = cohort_str.strip().split()
        if len(parts) == 2:
            semester = parts[0]
            try:
                year = int(parts[1])
                # Create Cohort object if it doesn't exist
                Cohort.objects.get_or_create(
                    name=cohort_str,
                    defaults={
                        'year': year,
                        'semester': semester,
                    }
                )
            except (ValueError, IndexError):
                print(f"Warning: Could not parse cohort string '{cohort_str}'")
        else:
            print(f"Warning: Unexpected cohort format '{cohort_str}'")


def reverse_populate_cohorts(apps, schema_editor):
    """Remove all Cohort objects (for migration rollback)"""
    Cohort = apps.get_model('tracker', 'Cohort')
    Cohort.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_cohort'),
    ]

    operations = [
        migrations.RunPython(populate_cohorts, reverse_populate_cohorts),
    ]
