# Generated by Django 5.2.7 on 2025-10-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_populate_cohorts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='cohort',
            new_name='cohort_str',
        ),
    ]
