# Generated by Django 5.2.7 on 2025-10-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_cohort_to_cohort_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainees', to='tracker.cohort'),
        ),
    ]
