# Generated by Django 5.2.7 on 2025-10-06 16:50

from django.db import migrations


def populate_trainee_cohort_fk(apps, schema_editor):
    """Link trainees to their Cohort objects based on cohort_str"""
    Trainee = apps.get_model('tracker', 'Trainee')
    Cohort = apps.get_model('tracker', 'Cohort')

    for trainee in Trainee.objects.all():
        if trainee.cohort_str:
            try:
                cohort = Cohort.objects.get(name=trainee.cohort_str)
                trainee.cohort = cohort
                trainee.save(update_fields=['cohort'])
            except Cohort.DoesNotExist:
                print(f"Warning: No cohort found for '{trainee.cohort_str}' (trainee {trainee.badge_number})")


def reverse_populate_trainee_cohort_fk(apps, schema_editor):
    """Clear cohort ForeignKey (for migration rollback)"""
    Trainee = apps.get_model('tracker', 'Trainee')
    Trainee.objects.all().update(cohort=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_cohort_fk'),
    ]

    operations = [
        migrations.RunPython(populate_trainee_cohort_fk, reverse_populate_trainee_cohort_fk),
    ]
