# Generated by Django 5.2.7 on 2025-10-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_populate_trainee_cohort_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='cohort_str',
        ),
        migrations.AlterField(
            model_name='trainee',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainees', to='tracker.cohort'),
        ),
    ]
