# Generated by Django 5.2.7 on 2025-10-06 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_finalize_cohort_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='is_current_override',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually set this cohort as current (overrides automatic detection)'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(db_index=True, help_text='e.g., Fall 2025', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., Security, Safety, Documentation', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(db_index=True, help_text='Display order (must be unique)', unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='badge_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='unsignlog',
            name='original_signed_at',
            field=models.DateTimeField(db_index=True, help_text='When original sign-off occurred'),
        ),
        migrations.AlterField(
            model_name='unsignlog',
            name='unsigned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['-year', '-semester'], name='cohort_year_semester_idx'),
        ),
        migrations.AddIndex(
            model_name='signoff',
            index=models.Index(fields=['trainee', 'signed_at'], name='signoff_trainee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='signoff',
            index=models.Index(fields=['signed_by', 'signed_at'], name='signoff_signer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active', 'order'], name='task_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category', 'is_active'], name='task_category_active_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['cohort', 'is_active'], name='trainee_cohort_active_idx'),
        ),
        migrations.AddIndex(
            model_name='trainee',
            index=models.Index(fields=['last_name', 'first_name'], name='trainee_name_idx'),
        ),
        migrations.AddIndex(
            model_name='unsignlog',
            index=models.Index(fields=['trainee', '-unsigned_at'], name='unsignlog_trainee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='unsignlog',
            index=models.Index(fields=['unsigned_by', '-unsigned_at'], name='unsignlog_unsigner_date_idx'),
        ),
    ]
