# Generated by Django 5.2.7 on 2025-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_cohort_is_current_override_alter_cohort_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-year', 'semester']},
        ),
        migrations.RemoveIndex(
            model_name='cohort',
            name='cohort_year_semester_idx',
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['-year', 'semester'], name='cohort_year_semester_idx'),
        ),
    ]
