# Generated by Django 5.2.7 on 2025-10-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_fix_cohort_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-year', '-semester_order']},
        ),
        migrations.RemoveIndex(
            model_name='cohort',
            name='cohort_year_semester_idx',
        ),
        migrations.AddField(
            model_name='cohort',
            name='semester_order',
            field=models.IntegerField(db_index=True, default=1, help_text='Numeric order for sorting: Spring=1, Fall=2'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['-year', '-semester_order'], name='cohort_year_semester_idx'),
        ),
    ]
