# Generated by Django 5.2.7 on 2025-10-06 18:29

from django.db import migrations


def populate_semester_order(apps, schema_editor):
    """Populate semester_order field for existing cohorts"""
    Cohort = apps.get_model('tracker', 'Cohort')
    for cohort in Cohort.objects.all():
        cohort.semester_order = 2 if cohort.semester == 'Fall' else 1
        cohort.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_add_semester_order_field'),
    ]

    operations = [
        migrations.RunPython(populate_semester_order, reverse_code=migrations.RunPython.noop),
    ]
