# Generated by Django 5.2.7 on 2025-10-20 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_populate_semester_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='notes',
            field=models.TextField(blank=True, help_text='Any comments or notes', max_length=10000),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='score',
            field=models.CharField(blank=True, help_text='Quiz score if applicable (e.g., 95, 95.5)', max_length=20, validators=[django.core.validators.RegexValidator(message='Score must be a valid number (e.g., 95, 95.5, 100.00)', regex='^\\d+(\\.\\d{1,2})?$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='unsignlog',
            name='original_notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='unsignlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for removal', max_length=10000),
        ),
    ]
