# Generated by Django 5.2.7 on 2025-10-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_signoff_notes_alter_signoff_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedTrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('allows_custom_type', models.BooleanField(default=False, help_text="True for 'Other Training' categories that have custom type field")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Advanced Training Type',
                'verbose_name_plural': 'Advanced Training Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Operator', 'Operator'), ('Student', 'Student'), ('Trainee', 'Trainee'), ('Staff', 'Staff'), ('Faculty', 'Faculty'), ('HP', 'Health Physics'), ('Other', 'Other')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False for removed/past staff')),
            ],
            options={
                'verbose_name': 'Advanced Training Staff',
                'verbose_name_plural': 'Advanced Training Staff',
                'ordering': ['badge_number'],
                'indexes': [models.Index(fields=['is_active', 'role'], name='adv_staff_active_role_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdvancedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, db_index=True, help_text='Date training was completed', null=True)),
                ('approver_initials', models.CharField(blank=True, help_text="Initials of staff who approved (e.g., 'ET', 'AS')", max_length=10)),
                ('termination_date', models.DateField(blank=True, help_text='Date training expires or was terminated', null=True)),
                ('custom_type', models.CharField(blank=True, help_text="Custom type for 'Other Training' (e.g., 'Package', 'Experiment', 'Waste')", max_length=100)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='tracker.advancedstaff')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='tracker.advancedtrainingtype')),
            ],
            options={
                'verbose_name': 'Advanced Training Record',
                'verbose_name_plural': 'Advanced Training Records',
                'ordering': ['-completion_date'],
                'indexes': [models.Index(fields=['staff', 'training_type'], name='adv_train_staff_type_idx'), models.Index(fields=['completion_date'], name='adv_train_completion_idx'), models.Index(fields=['termination_date'], name='adv_train_termination_idx')],
                'unique_together': {('staff', 'training_type', 'custom_type')},
            },
        ),
    ]
