# Generated by Django 5.2.7 on 2025-10-27 15:15

from django.db import migrations


def populate_training_types(apps, schema_editor):
    """Populate advanced training types from Excel structure"""
    AdvancedTrainingType = apps.get_model('tracker', 'AdvancedTrainingType')

    training_types = [
        {'name': 'KP Training', 'order': 1, 'allows_custom_type': False},
        {'name': 'Escort Training', 'order': 2, 'allows_custom_type': False},
        {'name': 'ExpSamp Training', 'order': 3, 'allows_custom_type': False},
        {'name': 'Other Training', 'order': 4, 'allows_custom_type': True},
        {'name': 'Other Training 2', 'order': 5, 'allows_custom_type': True},
    ]

    for training_type_data in training_types:
        AdvancedTrainingType.objects.get_or_create(**training_type_data)


def reverse_populate_training_types(apps, schema_editor):
    """Remove all training types on reverse migration"""
    AdvancedTrainingType = apps.get_model('tracker', 'AdvancedTrainingType')
    AdvancedTrainingType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_advancedtrainingtype_advancedstaff_advancedtraining'),
    ]

    operations = [
        migrations.RunPython(populate_training_types, reverse_populate_training_types),
    ]
