# Generated by Django 5.2.7 on 2025-10-27 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_populate_advanced_training_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedtrainingtype',
            name='authorized_signers',
            field=models.ManyToManyField(blank=True, help_text='Specific staff members authorized to sign off this training type. Leave empty to allow all staff.', related_name='authorized_advanced_training_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
