# Generated by Django 5.2.7 on 2025-10-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_add_authorized_signers_to_advanced_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedtraining',
            name='signed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when training was signed off in the system', null=True),
        ),
    ]
