# Generated by Django 5.2.7 on 2025-10-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_add_signed_at_to_advanced_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedtraining',
            options={'ordering': ['-completion_date'], 'permissions': [('manage_advanced_training', 'Can manage advanced training records')], 'verbose_name': 'Advanced Training Record', 'verbose_name_plural': 'Advanced Training Records'},
        ),
    ]
